DROP DATABASE IF EXISTS EMPLOYEES_DB;

CREATE DATABASE EMPLOYEES_DB;

CREATE TABLE DEPARTMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30),
 -- PRIMARY KEY(ID)
);

CREATE TABLE ROLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(30) NOT NULL,
    SALARY DECIMAL NOT NULL,
    DEPARTMENT_ID INT,
    FOREIGN KEY(DEPARTMENT_ID) REFERENCE DEPARTMENT(ID)
);

CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    ROLE_ID INT,
    FOREIGN KEY(ROLE_ID) REFERENCE ROLE(ID),
    MANAGER_ID INT FOREIGN KEY(EMPLOYEE) REFERENCE(ID)
);